---
# Cambiar nombre de equipo
- name: Asignar nombre de equipo
  hostname: name={{ inventory_hostname }}

- name: Asociar dirección de loopback
  lineinfile: dest=/etc/hosts line='127.0.1.1 {{ inventory_hostname }}' owner=root group=root mode=0644

